version: '3.4'

services:
  app:
    # TODO: refactor /web_app/web_app
    command: adev runserver /web_app/web_app
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - '4444:8000'
    volumes:
      - ./web_app:/web_app/web_app
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
  db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      # TODO: refactor env variable
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: root
      POSTGRES_DB: test_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
