version: '3.4'

services:
  app:
    command: gunicorn --workers=4 --bind 0.0.0.0:8000 main:create_app() --worker-class aiohttp.GunicornWebWorker
    build:
      context: .
    ports:
      - '4444:8000'
    volumes:
      - ./web_app:/web_app
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: db
      DB_USERNAME: ${APP_DB_USERNAME}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_DATABASE: ${APP_DB_DATABASE}
  db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${APP_DB_USERNAME}
      POSTGRES_USER: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
